### ISSUE TITLE
Discussion: Split dual-output devices into two HA devices?

### ISSUE THREAD

**Issue by SweVictor** [icanos/hassio-plejd#193]
Hi all,
The last few code changes have brought up the question _Should multi-output Plejd devices create one or may devices in Home Assistant_. Multiple _entities_ will always be created (one per output/sensor/...), but there is a choice in how to group these.

From the [Home Assistant glossary](https://www.home-assistant.io/docs/glossary/):

* **Device:** A device is usually a physical unit which can do or observe something.
* **Entity:** An entity is the representation of a function of a single device, unit, or web service. There may be multiple entities for a single device, unit, or web service, or there may be only one.

This question relates mostly to dual output devices, such as DIM-02 and REL-02. Plejd devices also have inputs, but in the current Bluetooth implementation it is typically not possible to listen to inputs from devices. Exceptions are wireless devices such as WPH-01 and WRT-01. 

## Option 1: One HA device, multiple entities (current implementation) ##

The current implementation creates _one HA device per physical Plejd device_. It then creates one _entity_ per output. So the DIM-02 would have one device with two entities (one per output) owned by it.

## Option 2: Multiple HA devices, one entity per device ##

A request for change put forward in a few places is to instead create _one HA device per output or function_. Each device would then have only one entity.

## Pros and cons ##

This issue is meant for discussion, so please pitch in! I'll ping some contributors as well as few people that has been active recently: @icanos, @JohnPhoto, @thomasloven, @xpatohr, @faanskit, 

A few pros for each solution, in my personal opinion:

Pros Option 1 (one device per physical Plejd unit)

* Matches how HA typically groups things (one temp/hum sensor has one device and one entity per sensor type, a washing machine has one device and a many entities, an alarm system has one alarm panel device with multiple entities)
* You get the two outputs as "related entities" in HA
* Even _if_ we would be able to get more input information from Plejd or get devices with A LOT of outputs, the amount of devices would still be limited to ~the number of physical Plejd devices in the system

Pros Option 2 (one device per output)

* Matches Plejd's naming convention and what's shown in the Plejd App (outputs are named, not physical devices)
* Makes device naming in HA more clear (currently the devices are named and renamed a bit randomly from the available outputs of each device, this could though be changed to always pick name of "output 1". Issues would still be that in Plejd you don't name devices, rather outputs)
* Makes it very easy to create `device`-based automations in HA, if using Option 1 you would instead create `entity`-based automations
* Room can be hinted per output (which is how Plejd groups rooms). For Option 1 you will need to override the room for entities not sharing room with the device.

An in-depth walkthrough can be seen at https://github.com/icanos/hassio-plejd/pull/179#issuecomment-834286512 (as well as the rest of that discussion for context). 

**So - the floor is yours! Thoughts?**

**Comment by faanskit** [comment]
My few cents:
- **Option A** preferred, provided the issues reported in [#179 (comment)](https://github.com/icanos/hassio-plejd/pull/179#issuecomment-834286512) is fixed. It is not acceptable (IMO) to not support the Ui Wizard for Automations and Scenes as it is right now.
- **Option B**, is the fallback if the above cannot be addressed
- **Option C** would be to leave it to the user to device (= configurable). As far as I've seen, its a one line check,

plejd/MqttClient.js, line 68:
```
if CONFIG == OPTION A:
    identifiers: `${device.deviceId}`,
elif CONFIG == OPTION B:
    identifiers: `${device.uniqueId}`,
```
Rationale for Option A (with fix for Ui automations and scenes): With DAL-01 supporting up to 64 units per device, **Option A** simply makes more sense.

This implies that some issues in Home Assistant needs to be fixed, which is where the issue _likely_ resides why Ui Wizard for Automations and Scenes does not work

**Comment by faanskit** [comment]
I actually think we can get some guidance from the HA developer documentation on [Device Registry](https://developers.home-assistant.io/docs/device_registry_index/):

_A device that offers multiple endpoints, where parts of the device sense or output in different areas, **should** be split into separate devices and refer back to parent device with the via_device attribute. This allows the separate endpoints to be assigned to different areas in the building._

For me, this reads **Option B** as the outputs of a DIM-02 / REL-02 / DAL-01 can be in different rooms (and areas).

But, what would then become the parent device in hassio-plejd? Naturally it should be the unit (DIM-02/REL-02), but how should it be registered over MQTT? MQTT Device Discovery does not offer anything of relevance.

> To challenge your preference for "Option 1" - how do you suggest handling the case when we can get som inputs from a device? Think conceptually of WPH-01 + two outputs - how would you suggest creating devices + entities?

Following the guidance from above; if the inputs "_sense or output in different areas_", also they should be devices. 
A WPH-10/WRT-01 will be a single device, with multiple actions (as it is right now). You cannot separate the inputs of such a device - unless you solder...
But, a input buttons from a DIM-01 can be considered own devices based on the above guidance. In theory it can be three different devices, but since the RTR-01 is physically connected to the unit it maybe can be limited to two if we solve the issue with `via_device`.


> Edit: Regarding your question on how to name things the current strategy of "latest report" is of course very strange. I think the "least bad" approach is to name the device output[0].name. 

I actually don't follow this.  I guess you mean `outputSettings[deviceId].output[0]`? Will this work also when the device is configured as "No load". Have not checked what is signaled.


Tough nut to crack this. My vote goes to Option B and ignore the `via_device` issue for now. This only based on usability aspects. If HA evolves, we'll change. Or, take the easy way out Option C.

**Comment by thomasloven** [comment]
I have raised this with the dev community in the [Home Assistant discord](https://discord.gg/home-assistant) for further input.

[Link to start of discussion](https://discord.com/channels/330944238910963714/554842238073700352/841264493131726868)

As you say, Option 1 is generally the recommended approach.
Further, DIM-02 and REL-02 are marketed as "kronbrytare" i.e. meant to connect to different bulbs in the same armature and light it up in two steps.

In reality, it will likely never be installed that way since a: large chandeliers are becoming increasingly rare in new installations and the whole concept is mostly a historical artifact and b: you can (often) just dim the bulbs if you want less light.

To me Option B makes more sense even if I don't know if connecting the two outputs to different rooms would be recommended or even legal (but IANAL/Electrician)...

**Comment by icanos** [comment]
For what it's worth, I'm leaning towards option B as well, simply because that is how Plejd works in its own ecosystem and seems to be like how HA does it when it comes to multiple input/output devices.

I'm also for skipping the `via_device` attribute for now since we don't have a master device so to say.

Love the work all of you have put into this, really appreciated and thoroughly done.

**Comment by faanskit** [comment]
Sorry for the confusion I created with A/B vs 1/2. I updated all my comments accordingly.

> To me Option B2 makes more sense even if I don't know if connecting the two outputs to different rooms would be recommended or even legal (but IANAL/Electrician)...

I checked with an Electrician just now. Rough translation:

_Reg. DIM-02/REL-02 there are no relevant regulations that prohibits to use one device for two different rooms. It is not however the current best practice. Usually you have one device per room and use wireless sync if you want to control from another room._

_In theory and in practice is is possible, if you want to do so._ 

_It is however commonly used like that  for outdoor lights._

E.g. REL-02 in a central location, controlling different "rooms" like _Porch_ and _Patio_

**Comment by SweVictor** [comment]
Good discussion. So - maybe "Option 2" has it's advantages after all...

Given that potential way forward I'm a bit "afraid" of the DAL-01, which is supposed to be able to control up to 64 loads in some way. Anyone knows anything about these?

https://brand.plejd.com/downloads/product-sheet/DAL-01/plejd_product_sheet_DAL-01_SV_FI.pdf

Dali standard: https://www.dali-alliance.org/dali/

**Comment by icanos** [comment]
That might be the device that is the exception that proves the rule? :-)

**Comment by faanskit** [comment]
> Given that potential way forward I'm a bit "afraid" of the DAL-01, which is supposed to be able to control up to 64 loads in some way. Anyone knows anything about these?

I hope to get some logs soon, but further discussion on that topic cannot take place in a public forum.

> That might be the device that is the exception that proves the rule? :-)

I expect it to behave like a "REL-64", but that will kill the BLE with the limitation of 255 id's.
Hopefully they have "sub-id's" defined on the BLE, the DAL-01 would most like be better off as 1 Device + 64 Entities.
