### ISSUE TITLE
Could not install the addon (Ubuntu 20.04.3 LTS + Docker)

### ISSUE THREAD

**Issue by fl0pp** [icanos/hassio-plejd#213]
I added the repository, and tried to install this addon (0.8.0-beta).
Then I get an error:
Could not install the addon
The command '/bin/bash -o pipefail -c npm install --no-audit --no-update-notifier --unsafe-perm' returned a non-zero code: 1

I am running this on an unsupported system (Ubuntu 20.04.3 LTS with Docker). Could that be the problem or is this addon specific?

OS: Ubuntu 20.04.3 LTS
Docker version: 20.10.8
HA: core-2021.8.8
Supervisor: supervisor-2021.06.8

Log:

```21-08-20 21:37:36 INFO (SyncWorker_1) [supervisor.docker.addon] Starting build for 4cb18a39/amd64-addon-plejd:0.8.0-beta
21-08-20 21:37:40 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build 4cb18a39/amd64-addon-plejd:0.8.0-beta: The command '/bin/bash -o pipefail -c npm install   --no-audit   --no-update-notifier   --unsafe-perm' returned a non-zero code: 1
21-08-20 21:37:40 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
Step 1/23 : ARG BUILD_FROM=hassioaddons/base:8.0.6


Step 2/23 : FROM $BUILD_FROM


 ---> 13cf499200eb

Step 3/23 : ENV LANG C.UTF-8


 ---> Using cache

 ---> c0abd1af95c3

Step 4/23 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]


 ---> Using cache

 ---> 35ec134930af

Step 5/23 : COPY ./*.js /plejd/


 ---> Using cache

 ---> e53a52a9b1d9

Step 6/23 : COPY ./config.json /plejd/


 ---> Using cache

 ---> 42aaf8a09cc5

Step 7/23 : COPY ./package.json /plejd/


 ---> Using cache

 ---> 5fdfc57b6a46

Step 8/23 : ARG BUILD_ARCH


 ---> Using cache

 ---> 2d9ae155bb6d

Step 9/23 : RUN apk add --no-cache jq


 ---> Using cache

 ---> c985d1948bb5

Step 10/23 : RUN   apk add --no-cache --virtual .build-dependencies   g++   gcc   libc-dev   linux-headers   make   python3   bluez   eudev-dev     && apk add --no-cache   git   nodejs   npm   dbus-dev   glib-dev     && npm config set unsafe-perm true


 ---> Using cache

 ---> 98d9070a9d23

Step 11/23 : WORKDIR /plejd


 ---> Using cache

 ---> 5bd4a67a5b08

Step 12/23 : RUN npm install   --no-audit   --no-update-notifier   --unsafe-perm


 ---> Running in 8d36e60efd91

npm
 ERR!
 dhis is not defined



npm
 
ERR!
 A complete log of this run can be found in:

npm
 ERR!
     /root/.npm/_logs/2021-08-20T19_37_39_767Z-debug.log

Removing intermediate container 8d36e60efd91```

**Comment by SweVictor** [comment]
Well... I am by no means a Docker guru so things related to that I'll leave to someone else. By the looks of it most things succeed, up until `npm install` (which adds NodeJS dependency packages). You can see what it installs in the code under `plejd/package.json`. Most things installed are JavaScript only and should cause no issues. 

The two somewhat hairy packages which do some kind of hardware interop are
- `@abandonware/bluetooth-hci-socket` - Bluetooth interop
- `dbus-next` - Dbus (Linux messaging bus) interop

Maybe you can look into any known issues with that and Ubuntu (Bluetooth issues would be my first bet). Since the above text also mentions a detailed log I'd have a look there as well.
