### ISSUE TITLE
Apparmor in latest version

### ISSUE THREAD

**Issue by djeskoswe** [icanos/hassio-plejd#74]
Hi 

Did have the 0.3.5 v running with apparmor = no , did upgrade to latest and added apparmar line but no go , see log

What im i doing wrong ? 

config = 

  "host_dbus": true,
  "apparmor": "no",

log =

node:290) UnhandledPromiseRejectionWarning: DBusError: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)
    at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:290) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Thanks

**Comment by icanos** [comment]
Try with:

"host_dbus": true,
"apparmor": true,

And see if that makes any difference.

**Comment by djeskoswe** [comment]
no go .... will uninstall it and restart all and see

**Comment by icanos** [comment]
Were you able to resolve this?

**Comment by djeskoswe** [comment]
No , but will do some more testing this week.

Thanks

**Comment by icanos** [comment]
Great! Have a look at this response and maybe try that :)
https://github.com/icanos/hassio-plejd/issues/70#issuecomment-596222193

**Comment by f0xenSWE** [comment]
Since the latest update of the addon I get the following error log: 

> [cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[08:01:19] INFO: Starting the Plejd service...
[08:01:19] INFO: Verified permissions on startup script
[services.d] done.
[08:01:19] INFO: Executing startup script
[08:01:19] INFO: Wrote plejd.json
[08:01:19] INFO: Running add-on
starting Plejd add-on v. 0.4.3
plejd-api: login()
plejd-api: logging into Fam Ågren
plejd-api: got session token response
plejd-api: getSites()
plejd-api: got site list response
plejd-api: getSites()
plejd-api: got site details response
wireEvents()
init()
(node:289) UnhandledPromiseRejectionWarning: DBusError: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)
    at _methodReturnHandlers.(anonymous function) (/plejd/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/plejd/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on (/plejd/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /plejd/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/plejd/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:289) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:289) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
plejd-mqtt: connected to mqtt.
plejd-mqtt: discovered light (DIM-02) named Taklampor with PID 12.
plejd-mqtt: discovered light (DIM-02) named Spotlights tak with PID 11.

I have tried to update the config.json file as follows: 

"host_dbus": true,
"apparmor": true,

and: 

"host_dbus": true,
"apparmor": "no",

Rebuild and restart of HA but the problem persists. 

Running hassio in docker.

**Comment by icanos** [comment]
Try with

"host_dbus": true,
"apparmor": false

**Comment by f0xenSWE** [comment]
Tried this, rebuild of addon and rebooted hassio but the problem persists.

**Comment by djeskoswe** [comment]
i have tried all the stuff i can now , it must be something in the new HA release ( running in docker and add-on local)

**Comment by djeskoswe** [comment]
updated to 107 and used :
  "host_dbus": true,
  "apparmor": false,

And all good.

Niklas
