### ISSUE TITLE
Pull request to plejd cloud

### ISSUE THREAD

**Issue by mattues** [icanos/hassio-plejd#88]
Plejd got in touch whit me regarding the session token requests the addon does. They are saying that i have done a few million requests. They are going to cut it down to 100 requests per 5 minute now. Is there a way to limit the requests?

**Comment by icanos** [comment]
I will look into it and rework the auth a bit

**Comment by icanos** [comment]
Not sure about what happened, but it seems that your plugin crashed and restarted quite a lot if you've been throwing a few million requests towards their api. The only time the plugin calls the Plejd API, is when authenticating on startup.

Might need some logs in order to investigate this further. I've been running the integration for about 4 months now without interruption.

**Comment by SweVictor** [comment]
Closing for now. Caching and reworked overall structure of the addon is probably what is needed to solve this once and for all. Changes the last month or so address stability, so this should be less of a problem nowadays.
